categories:
- Variant Analysis
homepage_url: https://software.broadinstitute.org/gatk/
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/gatk4
type: unrestricted
auto_tool_repositories:
  name_template: "gatk4_{{ tool_id }}"
  description_template: "Wrapper for the GATK 4 operation {{ tool_name }}."
suite:
  name: "suite_gatk_4"
  description: "A suite of tools bundling the GATK 4 package from Broad."
  type: repository_suite_definition