name: bioext
owner: veg
description: A few handy bioinformatics tools not already within BioPython
long_description: |
  Long description goes here.
remote_repository_url: https://github.com/davebx/bioext-gx/
homepage_url: https://pypi.python.org/pypi/biopython-extensions/
type: unrestricted
categories:
 - Next Gen Mappers
