categories:
- Assembly
description: Installs SPAdes wrappers
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
  Various features of the St. Petersburg assembler.
name: suite_spades_tools
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/suites/suite_spades_tools
type: repository_suite_definition
