categories:
- SAM
- Statistics
description: Provides simple stats on BAM files.
long_description: |
  This tool uses the SAMtools toolkit to produce simple stats on a BAM file.
name: samtools_flagstat
<<<<<<< HEAD
owner: iuc
=======
owner: devteam
>>>>>>> f8fb9deb0aa36e2bda92e2df8a4faac26ebdb722
homepage_url: http://www.htslib.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/samtools/samtools_flagstat
type: unrestricted
