name: Galaxy Tool Linting and Tests for push and PR
on: [push, pull_request]
env:
  GALAXY_REPO: https://github.com/galaxyproject/galaxy
  GALAXY_RELEASE: release_20.09
jobs:
  # the setup job does two things:
  # 1. cache the pip cache and .planemo
  # 2. determine the list of changed repositories
  # it produces one artifact which contains
  # - a file with the latest SHA from the chosen branch of the Galaxy repo
  # - a file containing the list of changed repositories
  # which are needed in subsequent steps.
  setup:
    name: Setup cache and determine changed repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Print github context properties
      run: |
        echo 'event: ${{ github.event_name }}'
        echo 'sha: ${{ github.sha }}'
        echo 'ref: ${{ github.ref }}'
        echo 'head_ref: ${{ github.head_ref }}'
        echo 'base_ref: ${{ github.base_ref }}'
        echo 'event.before: ${{ github.event.before }}'
        echo 'event.after: ${{ github.event.after }}'
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/download-artifact@v2
      with:
        name: Workflow artifacts
        path: ../workflow_artifacts/
    - name: Determine latest galaxy commit
      run: echo ::set-env name=GALAXY_HEAD_SHA::$(cat ../workflow_artifacts/galaxy.sha)
    - name: Cache .cache/pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
    - name: Cache .planemo
      uses: actions/cache@v2
      id: cache-planemo
      with:
        path: ~/.planemo
        key: planemo_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
    - name: Install Planemo
      run: pip install planemo
    - name: Planemo ci_find_tools
      run: |
        touch changed_repositories_chunk.list changed_tools_chunk.list
        if [ -s ../workflow_artifacts/changed_repositories.list ]; then
            if [ $(wc -l < ../workflow_artifacts/changed_repositories.list) -eq 1 ]; then
                planemo ci_find_tools --chunk_count 4 --chunk ${{ matrix.chunk }} \
                               --output changed_tools_chunk.list \
                               $(cat ../workflow_artifacts/changed_repositories.list)
            else
                planemo ci_find_repos --chunk_count 4 --chunk ${{ matrix.chunk }} \
                               --output changed_repositories_chunk.list \
                               $(cat ../workflow_artifacts/changed_repositories.list)
            fi
        fi
    - name: Show changed tools/repositories chunk list
      run: cat changed_tools_chunk.list changed_repositories_chunk.list
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
